### ISSUE TITLE
User names not colored when logged out

### ISSUE THREAD

**Issue by grubeninspekteur** [grubeninspekteur/BetterRBTV#45]
Affects most recent version from this repository.

**Comment by DoomDesign** [comment]
After my research I can conclude: This doesn't only apply to the colored user names, but rather ALL inserted CSS in all functions (no timestamps etc). Also, this problem seems to only appear when you are logged out!
I traced this back to the YouTubeLive.onChatLoaded function. Somehow this doesn't callback any functions of our extension correctly when logged out!

**Comment by grubeninspekteur** [comment]
Space saving & emotes work though. Also, this affects Chrome too.

**Comment by grubeninspekteur** [comment]
Tested in Chrome Incognito mode, no longer an issue.
